### ISSUE TITLE
Is it possible to download a Kallisto Index? 

### ISSUE THREAD

**Issue by zfrenchee** [ENCODE-DCC/rna-seq-pipeline#16]
The [docs](https://github.com/ENCODE-DCC/rna-seq-pipeline/blob/master/docs/howto.md#merge-annotation) mention building STAR, rsem, and kallisto indexes. They also mention how, for common references (e.g. hg38) you can download the star and rsem indexes. Is it possible to download the kallisto index for common references (e.g. from the ENCODE site) ?

**Comment by ottojolanki** [comment]
I am working on getting it released as soon as possible.

**Comment by ottojolanki** [comment]
That was faster than I expected :) GRCh38 version is downloadable [here](https://www.encodeproject.org/files/ENCFF904UYQ/).
