### ISSUE TITLE
$(which prep_kallisto.sh) returns nothing inside the singularity container

### ISSUE THREAD

**Issue by zfrenchee** [ENCODE-DCC/rna-seq-pipeline#17]
Seems like the script might not be appropriately symlinked inside the container perhaps? 

```
~ » singularity exec ~/.singularity/rna-seq-pipeline-v1.0.simg /bin/bash
:~$ $(which prep_kallisto.sh)
:~$
```

singularity container was downloaded via

```
singularity pull docker://quay.io/encode-dcc/rna-seq-pipeline
```

**Comment by ottojolanki** [comment]
You should find the correct path (`/software/rna-seq-pipeline/src/prep_kallisto.sh`) by running `which` in the usual manner: `which prep_kallisto.sh` (without parenthesis or $ sign). Please let me know how it goes.

**Comment by zfrenchee** [comment]
fixed by 
```
singularity pull docker://quay.io/encode-dcc/rna-seq-pipeline:v1.0
```
instead of 
```
singularity pull docker://quay.io/encode-dcc/rna-seq-pipeline
```
