### ISSUE TITLE
Set defaults in the rna-seq-pipeline.wdl for parity with ATAC/ChIP

### ISSUE THREAD

**Issue by zfrenchee** [ENCODE-DCC/rna-seq-pipeline#18]
The ATAC and ChIP pipelines have parameter defaults specified in the WDL, e.g.

https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/841867d3e188e0e3be9b8e3f45caf3ba4f1df041/atac.wdl#L118-L121

The RNA-Seq pipeline could use the same. Currently it reads like: 

https://github.com/ENCODE-DCC/rna-seq-pipeline/blob/31d6ee7d87f0743ab08e15a18327f7d400ec8dac/rna-seq-pipeline.wdl#L26-L30

This would help me specify fewer parameters via JSON at runtime, has parity with the other ENCODE pipelines here, and I think is clearer, ultimately.

**Comment by ottojolanki** [comment]
Thank you for the suggestion. Values of these parameters highly depend on the depth of the experiment and on the preferences of the user (speed vs cost) and for that reason I prefer to leave these not specified for now.

**Comment by zfrenchee** [comment]
@ottojolanki thanks for getting back. 

I think that's why it makes sense to add defaults, but keep them as parameters. For example, the parameters for cpu and RAM could be set by default as the minimum necessary to successfully execute the job. It would also be nice to have parity with the other pipelines in this regard.
