### ISSUE TITLE
Pipeline issues

### ISSUE THREAD

**Issue by zfrenchee** [ENCODE-DCC/rna-seq-pipeline#19]
I gave this pipeline a first test, and interestingly, it failed partway through: 

| | |
|-|-|
| "rna.align" | "executionStatus": "Done", | 
| "rna.bam_to_signals" | "executionStatus": "Done", | 
| "rna.rsem_quant" | "executionStatus": "Failed", | 
| "rna.kallisto" | "executionStatus": "Failed", | 
| "rna.rna_qc" | "executionStatus": "Failed", | 

rsem failed with the following error message: 

```
Job rna.rsem_quant:0:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /pool/data/cromwell-aals/cromwell-executions/rna/1181a070-5bf0-4f0a-b6f4-4a754c12c6f4/call-rsem_quant/shard-0/execution/stderr.
 2019-04-17 13:02:33,285 | INFO | __main__: Running RSEM command rsem-calculate-expression --bam --estimate-rspd --calc-ci --seed 12345 -p 2 --no-bam-output --ci-memory 4000 --forward-prob 0 --paired-end /pool/data/cromwell-aals/cromwell-executions/rna/1181a070-5bf0-4f0a-b6f4-4a754c12c6f4/call-rsem_quant/shard-0/inputs/-927098316/rep1PE_stranded_anno.bam rsem_index/rsem rep1PE_stranded_anno_rsem
Cannot open rep1PE_stranded_anno_rsem.temp/rep1PE_stranded_anno_rsem_alignable_1.fq! It may not exist.
Traceback (most recent call last):
  File "/software/rna-seq-pipeline/src/rsem_quant.py", line 135, in <module>
    main(args)
  File "/software/rna-seq-pipeline/src/rsem_quant.py", line 107, in main
    gene_quant_fn)
  File "/software/rna-seq-pipeline/src/rsem_quant.py", line 83, in calculate_number_of_genes_detected
    quants = pd.read_csv(quant_tsv, sep='\t')
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'rep1PE_stranded_anno_rsem.genes.results' does not exist
ln: failed to access '*.genes.results': No such file or directory
ln: failed to access '*.isoforms.results': No such file or directory
ln: failed to access '*_number_of_genes_detected.json': No such file or directory
```

kallisto seems to have potentially failed independently with the following error message: 
```
2019-04-17 13:02:07,063 | INFO | __main__: Running kallisto command: kallisto quant -i /pool/data/cromwell-aals/cromwell-executions/rna/1181a070-5bf0-4f0a-b6f4-4a754c12c6f4/call-kallisto/shard-0/inputs/276101194/genome -o kallisto_out -t 2 --plaintext --rf-stranded /pool/data/cromwell-aals/cromwell-executions/rna/1181a070-5bf0-4f0a-b6f4-4a754c12c6f4/call-kallisto/shard-0/inputs/2079390556/ALS-0BUU_diMN32_rep1_1.fastq /pool/data/cromwell-aals/cromwell-executions/rna/1181a070-5bf0-4f0a-b6f4-4a754c12c6f4/call-kallisto/shard-0/inputs/2079390556/ALS-0BUU_diMN32_rep1_2.fastq

[quant] fragment length distribution will be estimated from the data
Error: incompatible indices. Found version 0, expected version 10
Rerun with index to regenerateTraceback (most recent call last):
  File "/software/rna-seq-pipeline/src/kallisto_quant.py", line 239, in <module>
    main(args)
  File "/software/rna-seq-pipeline/src/kallisto_quant.py", line 196, in main
    kallisto_quantifier.rename_output()
  File "/software/rna-seq-pipeline/src/kallisto_quant.py", line 102, in rename_output
    self.out_prefix + '_abundance.tsv'))
FileNotFoundError: [Errno 2] No such file or directory: '/pool/data/cromwell-aals/cromwell-executions/rna/1181a070-5bf0-4f0a-b6f4-4a754c12c6f4/call-kallisto/shard-0/execution/kallisto_out/abundance.tsv' -> '/pool/data/cromwell-aals/cromwell-executions/rna/1181a070-5bf0-4f0a-b6f4-4a754c12c6f4/call-kallisto/shard-0/execution/kallisto_out/rep1PE_stranded_abundance.tsv'
ln: failed to access 'kallisto_out/*_abundance.tsv': No such file or directory
```

In the cromwell logs (not in any tool's stderr) I also saw: 
```
Could not localize transcript_id_to_gene_type_mappings/gencodeV24pri-tRNAs-ERCC-phiX.transcript_id_to_genes.tsv -> /pool/data/cromwell-aals/cromwell-executions/rna/1181a070-5bf0-4f0a-b6f4-4a754c12c6f4/call-rna_qc/shard-0/inputs/-2126377838/gencodeV24pri-tRNAs-ERCC-phiX.transcript_id_to_genes.tsv:
        transcript_id_to_gene_type_mappings/gencodeV24pri-tRNAs-ERCC-phiX.transcript_id_to_genes.tsv doesn't exist
        File not found /pool/data/cromwell-aals/cromwell-executions/rna/1181a070-5bf0-4f0a-b6f4-4a754c12c6f4/call-rna_qc/shard-0/inputs/-2126377838/gencodeV24pri-tRNAs-ERCC-phiX.transcript_id_to_genes.tsv -> /pool/data/cromwell-aals/transcript_id_to_gene_type_mappings/gencodeV24pri-tRNAs-ERCC-phiX.transcript_id_to_genes.tsv
        File not found transcript_id_to_gene_type_mappings/gencodeV24pri-tRNAs-ERCC-phiX.transcript_id_to_genes.tsv
        File not found /pool/data/cromwell-aals/transcript_id_to_gene_type_mappings/gencodeV24pri-tRNAs-ERCC-phiX.transcript_id_to_genes.tsv
```
Which is a little strange since that path exists, and the other reference files are all accessible. 

**update**: the failure to localize the file is what seems to have caused `rna_qc` to fail. 

How might I fix these?

**Comment by ottojolanki** [comment]
Hi. I would need couple of things to start pinpointing the reason of all this. Could you show me your `input.json`, and the command line you used to start the run? Also I would like to know which platform you are running on and whether you are using Docker (version?) or Singularity (version?).

**Comment by zfrenchee** [comment]
@ottojolanki 

Command: 
```
curl -X POST --header "Accept: application/json" -v "0.0.0.0:8000/api/workflows/v1/batch" \
  -F workflowSource=@../../encode3-pipelines/rna-seq-pipeline/rna-seq-pipeline.wdl \
  -F workflowInputs=@rna_trial.json \
  -F workflowOptions=@singularity.json
```
Json: 
```
[
    {
        "rna.endedness" : "paired",
        "rna.fastqs_R1" : [ "/pool/data/globus/transcriptomics/1_fastq/6_protocol_selection/diMN32/ALS-0BUU_diMN32_rep1_1.fastq" ],
        "rna.fastqs_R2" : [ "/pool/data/globus/transcriptomics/1_fastq/6_protocol_selection/diMN32/ALS-0BUU_diMN32_rep1_2.fastq" ],

        "rna.aligner" : "star",
        "rna.align_index" : "/pool/data/cromwell-aals/encode3-pipelines/genome/star_index/hg38_STAR_index.tar.gz",

        "rna.bamroot" : "PE_stranded",
        "rna.strandedness" : "stranded",
        "rna.strandedness_direction" : "reverse",
        "rna.chrom_sizes" : "/pool/data/cromwell-aals/encode3-pipelines/genome/hg38.chrom.sizes",

        "rna.align_ncpus" : 2,
        "rna.align_ramGB" : 4,
        "rna.align_disk" : "local-disk 20 HDD",

        "rna.kallisto_index" : "/pool/data/cromwell-aals/encode3-pipelines/genome/kallisto_index/GRCh38_reference_genome.idx",
        "rna.kallisto_number_of_threads" : 2,
        "rna.kallisto_ramGB" : 4,
        "rna.kallisto_disk" : "local-disk 20 HDD",

        "rna.rna_qc_tr_id_to_gene_type_tsv" : "/pool/data/cromwell-aals/encode3-pipelines/genome/transcript_id_to_gene_type_mappings/gencodeV24pri-tRNAs-ERCC-phiX.transcript_id_to_genes.tsv",
        "rna.rna_qc_disk" : "local-disk 20 HDD",

        "rna.bam_to_signals_ncpus" : 1,
        "rna.bam_to_signals_ramGB" : 2,
        "rna.bam_to_signals_disk" : "local-disk 20 HDD",

        "rna.rsem_index" : "/pool/data/cromwell-aals/encode3-pipelines/genome/rsem_index/GRCh38_rsem_index.tar.gz",
        "rna.rsem_ncpus" : 2,
        "rna.rsem_ramGB" : 4,
        "rna.rsem_disk" : "local-disk 20 HDD",

        "rna.mad_qc_disk" : "local-disk 20 HDD"
    }
]
```

Cromwell: `cromwell-34.jar`
Singularity: `singularity version 3.1.0-52.g3e3c113`

**Comment by ottojolanki** [comment]
Thank you. One question about your reference files (indexes and chrom sizes), did you use [this](https://www.encodeproject.org/references/ENCSR425FOI/) for chroms, [this](https://www.encodeproject.org/files/ENCFF742NER/) for STAR and [this](https://www.encodeproject.org/files/ENCFF940AZB/) for RSEM and [this](https://www.encodeproject.org/files/ENCFF904UYQ/) for kallisto (I really need to make those easier to find, TODO for next version of docs..)? Another thing I would like to know is how deep are your experiments sequenced?

**Comment by zfrenchee** [comment]
@ottojolanki 

- I used the reference files you linked, except for Kallisto, which I built myself (#16).
- My un-gzipped fastqs are about 8GB R1 / 8GB R2

**Comment by zfrenchee** [comment]
I tried again with the downloaded Kallisto index, and the pipeline still fails. The major issue seems to be with `rsem` (same as above): 
```
2019-04-18 18:55:44,089 | INFO | __main__: Running RSEM command rsem-calculate-expression --bam --estimate-rspd --calc-ci --seed 12345 -p 2 --no-bam-output --ci-memory 4000 --forward-prob 0 --paired-end /pool/data/cromwell-aals/cromwell-executions/rna/e4e1612b-11b6-4715-8edb-d15dc9bf0b95/call-rsem_quant/shard-0/inputs/-81271415/rep1PE_stranded_anno.bam rsem_index/rsem rep1PE_stranded_anno_rsem
Cannot open rep1PE_stranded_anno_rsem.temp/rep1PE_stranded_anno_rsem_alignable_1.fq! It may not exist.
Traceback (most recent call last):
  File "/software/rna-seq-pipeline/src/rsem_quant.py", line 135, in <module>
    main(args)
  File "/software/rna-seq-pipeline/src/rsem_quant.py", line 107, in main
    gene_quant_fn)
  File "/software/rna-seq-pipeline/src/rsem_quant.py", line 83, in calculate_number_of_genes_detected
    quants = pd.read_csv(quant_tsv, sep='\t')
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'rep1PE_stranded_anno_rsem.genes.results' does not exist
ln: failed to access '*.genes.results': No such file or directory
ln: failed to access '*.isoforms.results': No such file or directory
ln: failed to access '*_number_of_genes_detected.json': No such file or directory
```

I'm not totally clear based on this error message whether the original missing file is `rep1PE_stranded_anno_rsem.genes.results` or `rep1PE_stranded_anno_rsem.temp/rep1PE_stranded_anno_rsem_alignable_1.fq`. The first of those seems to be an output of rsem, so I'm tempted to believe that's not the error. 

https://github.com/ENCODE-DCC/rna-seq-pipeline/blob/31d6ee7d87f0743ab08e15a18327f7d400ec8dac/rna-seq-pipeline.wdl#L242

Where is `rep1PE_stranded_anno_rsem.temp/rep1PE_stranded_anno_rsem_alignable_1.fq` supposed to come from?

**Comment by ottojolanki** [comment]
Thank you for this info. You should use gzipped fastqs (Encode uses them directly from that format and it had not occured to me that someone would want to do otherwise. I'll consider making gzipping optional in later versions. STAR is explicitly told to use `zcat` when handling input, so that may be the first problem here.).
 
Another thing that would take one variable away from the debugging process would be using the kallisto index from ENCODE portal.
 
The resources are probably not enough for the alignment to finish succesfully (STAR hogs a lot of memory). I would consider giving it something in the order of 8 cores and 32GB of memory, same goes for RSEM. kallisto could use a bit more than you are giving (4cpu/8GB ish). bam_to_signals varies quite a lot from experiment to experiment but i would try 2cpu and 8GB. 

Disk resource parameters should be expanded as well to be able to fit the outputs and inputs keeping in mind that (I am not super familiar how the big index files get linked on HPC as I do almost everything in cloud nowadays) STAR index is almost 25GB, you are producing bam files that can be 10GB each(you make 2 of these per replicate) etc. Allocating 100GB for alignment and quantitation may not be a big overstatement. 

Thank you for your patience, please let me know how it goes.

**Comment by ottojolanki** [comment]
Can you try again with all the things above. I think the problem may actually be already in STAR that sometimes quietly fails to produce good outputs when running out of memory. `rep1PE_stranded_anno_rsem.temp/rep1PE_stranded_anno_rsem_alignable_1.fq` is some internal temporary file rsem makes for its own purposes.

**Comment by zfrenchee** [comment]
Thanks @ottojolanki 

Note the parameters I used are lifted directly from the [howto docs](https://github.com/ENCODE-DCC/rna-seq-pipeline/blob/master/docs/howto.md). If those aren't sufficient resources as you describe in your previous comment, it may make sense to update the docs, or add sensible defaults to the WDL (#18). 

In this last attempt, I 
- gzipped my fastqs
- downloaded the ENCODE kallisto index
- 
        "rna.align_ncpus" : 8,
        "rna.align_ramGB" : 32,
- 
        "rna.kallisto_number_of_threads" : 4,
        "rna.kallisto_ramGB" : 8,

- Gave every task `"local-disk 100 HDD",` for disk

The workflow is running.

**Comment by ottojolanki** [comment]
@zfrenchee First of all, great that you got the pipeline running and thank you for all the suggestions. As of adding the defaults, I am hesitant to add them because of reasons I elaborated in [issue #18](https://github.com/ENCODE-DCC/rna-seq-pipeline/issues/18). I will however, in an attempt to stay flexible but at the same time respond to the issue you are raising, add a full data use case in the docs with defaults that users can use as pointers towards finding resource settings that suit them. Thank you!

**Comment by zfrenchee** [comment]
@ottojolanki 

- How many cores / how much RAM should rsem be allocated? I'm saying: 
```
        "rna.rsem_ncpus": 2,
        "rna.rsem_ramGB": 4,
```

- Should it be the slowest part of the pipeline? It is for me.
