### ISSUE TITLE
Support un-gzipped fastqs. 

### ISSUE THREAD

**Issue by zfrenchee** [ENCODE-DCC/rna-seq-pipeline#20]
The ENCODE [ATAC](https://github.com/ENCODE-DCC/atac-seq-pipeline) and [ChIP](https://github.com/ENCODE-DCC/chip-seq-pipeline2) pipelines both support un-gzippped fastqs. (i.e. `.fastq` instead of `.fastq.gz`). Our consortium ([AnswerALS](https://www.answerals.org/)) gets our fastqs un-gzipped, and I suspect many others do as well. It seems reasonable to add this as an option to the RNA-Seq workflow as well.

**Comment by ottojolanki** [comment]
I will consider adding this in a later version. Thank you for the suggestion!

**Comment by zfrenchee** [comment]
@ottojolanki might make sense to leave it as an open issue, since someone else might take it on, and it isn't "fixed" per se.
