### ISSUE TITLE
Missing file genomeParameters.txt

### ISSUE THREAD

**Issue by vsoch** [ENCODE-DCC/rna-seq-pipeline#31]
I am missing a file called "genomeParameters.txt" and it's supposed to be in the --genomeDir? I've looked across the repository and in the portal and I can't find any documentation about it. How do I generate or obtain this file?

**Comment by ottojolanki** [comment]
Hi, can you show me your inputs and the error message you are getting? Which platform are you running on?
Thank you.

**Comment by ottojolanki** [comment]
That file is actually a part of the STAR index  and you should not have to worry about it. The index can be downloaded from https://www.encodeproject.org/references/ENCSR314WMD/.

**Comment by vsoch** [comment]
Thanks that's exactly what I needed! Just to verify before I download a monster file, I need "genome index | GRCh38" correct? 

What I'll do is have a step in the workflow to handle this for the user given that it's not found.

**Comment by vsoch** [comment]
And apologies for stupid questions - I don't have background in genomics.

**Comment by vsoch** [comment]
And another quick question - where in the docs does it mention needing to do this? I think I missed it.

**Comment by ottojolanki** [comment]
It would have been mentioned in the https://github.com/ENCODE-DCC/rna-seq-pipeline/blob/master/docs/reference.md#genome-files 
For Homo Sapiens experiments, the GRCh38 is the correct one (https://www.encodeproject.org/files/ENCFF742NER/).

**Comment by vsoch** [comment]
ah ok, I was going off of the example input, and I definitely have the

**Comment by ottojolanki** [comment]
Thank you, making the indexes findable in the documentation is something I have changed already couple of times and looks like I still need to do a better job at it. I'll release a new version soonish and I'll put some extra thought in improving this aspect of documentation for that.

**Comment by vsoch** [comment]
hey @ottojolanki I have another question - I clicked here looking for the STAR index - https://www.encodeproject.org/files/ENCFF742NER/ I downloaded the huge .tar.gz "ENCFF742NER.tar.gz " yesterday and  (per the example input data) I'm looking for a file called `data/test/GRCh38_v24_ERCC_phiX_starIndex_chr19only.tgz`. In the top of the link I see that the original file name is the one that I seek:

![image](https://user-images.githubusercontent.com/814322/64618809-f59d2e80-d3ae-11e9-9ee6-e13a7fd93af2.png)

But I don't see anything with star in any of the options to download. When I extract the download for the .tar.gz I see a folder like this (called "out"):

```
Genome                    chrLength.txt             chrStart.txt              geneInfo.tab              sjdbList.fromGTF.out.tab  transcriptInfo.tab
SA                        chrName.txt               exonGeTrInfo.tab          genomeParameters.txt      sjdbList.out.tab          
SAindex                   chrNameLength.txt         exonInfo.tab              sjdbInfo.txt              star_bamCommentLines.txt
```
And this is indeed where the genomeParameters.txt is hiding, however one of the inputs I need must be a .tar.gz, and (I had intuited) is called `GRCh38_v24_ERCC_phiX_starIndex_chr19only.tgz` Does the script expect `ENCFF742NER.tar.gz` to be this file? Why would I need to pass both the directory and the .tar.gz in this case? Or is there a place to download the correctly named file that I'm missing? Thanks!

**Comment by ottojolanki** [comment]
`ENCFF742NER.tar.gz` is the expected file. You need not define the optional parameter for the directory, everything works out of the box for files from ENCODE. The parameter is actually something I am going to remove altogether from the pipeline in the next version. The idea in including that option was to facilitate using index files that were generated by someone else, possibly with differently structured tar-archive (depending on the options they used when generating the index with something else than the index generating workflows here). Your confusion echoes the confusion of other users about the parameter, and makes me even more confident that removing it is a good idea. Thanks!

**Comment by vsoch** [comment]
cool, makes perfect sense, thank you!
