### ISSUE TITLE
How can I resume the pipeline after fixing the error? 

### ISSUE THREAD

**Issue by rdbcasillas** [ENCODE-DCC/rna-seq-pipeline#46]
I had to fix my input.json file which was causing an error. Since a lot of analysis was already performed, how can I resume the pipeline from the point of failure instead of starting it all over? I understand that metadata json will have some info on this but I couldn't find anything in the documentation on how to do this.

**Comment by ottojolanki** [comment]
We rely on Cromwell server's call caching functionality to do this. It is on by default when running with caper in server mode. For more information see https://cromwell.readthedocs.io/en/develop/Configuring/#call-caching
