### ISSUE TITLE
Error (Cromwell): Failed to run rna.align and rna.kallisto

### ISSUE THREAD

**Issue by firdaaminy** [ENCODE-DCC/rna-seq-pipeline#50]
Hello again.

First I would like to thank you for the thorough explanation I received regarding the issue I encounter with Caper a couple of weeks ago. Fortunately, with your help, I was able to solve the issue by re-installing Caper, Cromwell, and Womtool to the newest version. I am finally able to submit and run the pipeline without encountering the error message of WDL or input JSON is invalid.

So I tried to submit the workflow to the system using the command `caper submit [workflow]`. But a problem began to arise when I run the pipeline at the same time with the command `caper run rna-seq-pipeline.wdl -i input.json -b gcp -m testrun_metadata.json`. I noticed that when the Cromwell initializing rna.align and rna.kallisto, it showed these errors message:
`cromwell-system-akka.dispatchers.backend-dispatcher-35 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID(39bfdaee)rna.align:1:2]: Status change from - to Failed` and the same with the rna.kallisto.

I also changed the input.json from the tutorial to
{
    "rna.endedness" : "paired",
    "rna.fastqs_R1" : [["gs://rna_caper/inputs/ENCSR653DFZ_rep1_chr19_10000reads_R1.fastq.gz"], ["gs://rna_caper/inputs/ENCSR653DFZ_rep2_chr19_10000reads_R1.fastq.gz"]],
    "rna.fastqs_R2" : [["gs://rna_caper/inputs/ENCSR653DFZ_rep1_chr19_10000reads_R2.fastq.gz"], ["gs://rna_caper/inputs/ENCSR653DFZ_rep2_chr19_10000reads_R2.fastq.gz"]],
    "rna.align_index" : "gs://rna_caper/reference/GRCh38_v24_ERCC_phiX_starIndex_chr19only.tgz",
    "rna.rsem_index" : "gs://rna_caper/reference/GRCh38_v24_ERCC_phiX_rsemIndex_chr19only.tgz",
    "rna.kallisto_index" : "gs://rna_caper/reference/Homo_sapiens.GRCh38.cdna.all.chr19_ERCC_phix_k31_kallisto.idx",
    "rna.bamroot" : "PE_stranded",
    "rna.strandedness" : "stranded",
    "rna.strandedness_direction" : "reverse",
    "rna.chrom_sizes" : "gs://rna_caper/reference/GRCh38_EBV.chrom.sizes",
    "rna.align_ncpus" : 16,
    "rna.align_ramGB" : 60,
    "rna.rsem_ncpus" : 16,
    "rna.rsem_ramGB" : 60,
    "rna.kallisto_number_of_threads" : 8,
    "rna.kallisto_ramGB" : 30,
    "rna.rna_qc_tr_id_to_gene_type_tsv" : "gs://rna_caper/reference/gencodeV24pri-tRNAs-ERCC-phiX.transcript_id_to_genes.tsv",
    "rna.bam_to_signals_ncpus" : 8,
    "rna.bam_to_signals_ramGB" : 30,
    "rna.align_disk" : "local-disk 100 HDD",
    "rna.kallisto_disk" : "local-disk 100 HDD",
    "rna.rna_qc_disk" : "local-disk 100 HDD",
    "rna.bam_to_signals_disk" : "local-disk 100 HDD",
    "rna.mad_qc_disk" : "local-disk 100 HDD",
    "rna.rsem_disk" : "local-disk 100 HDD"
}

What could be the possible issue here causing that error? Does the change in the input.json has anything to do with the error? I hope if you don't mind, you could give me some insight on this problem.

Thank you very much for your understanding and your help

**Comment by leepc12** [comment]
Please attach a full screen log from Caper and the default conf file ~/.caper/default.conf.

**Comment by firdaaminy** [comment]
Hello, thanks for your reply

Here is the Caper screen log:
![image](https://user-images.githubusercontent.com/13981074/69589426-627ba880-102f-11ea-829e-d3f874426344.png)

Here is the failed initialization of rna.align
![image](https://user-images.githubusercontent.com/13981074/69589522-a8387100-102f-11ea-99e5-143e2555ea38.png)

And here is my default conf file ~/.caper/default.conf
![image](https://user-images.githubusercontent.com/13981074/69589903-06b21f00-1031-11ea-9823-64e07727f6fd.png)

I also changed some of the codes in the input.json file. I changed it because I read in your Github "Resource" section, it is said that alignment is going to be the most memory-intensive task, quantitation with RSEM is going to be computationally hardest, kallisto will require some non-trivial amount of resources. Therefore, I changed the memory and the CPUs allocation into:
`{
    "rna.align_ncpus" : 16,
    "rna.align_ramGB" : 60,
    "rna.rsem_ncpus" : 16,
    "rna.rsem_ramGB" : 60,
    "rna.kallisto_number_of_threads" : 8,
    "rna.kallisto_ramGB" : 30,
    "rna.bam_to_signals_ncpus" : 8,
    "rna.bam_to_signals_ramGB" : 30
}`
And changed all the local disk to "local-disk 100 HDD". Does the change have anything to do with the error?

Thank you for your help and your understanding

**Comment by leepc12** [comment]
I wanted to see a full text log (not a screenshot).

I didn't write this pipeline's WDL (I wrote Caper though) but `100 HDD` can be too small for large tasks.

**Comment by firdaaminy** [comment]
Here is the full-text log from when I submitted the workflow
[screenlog1.txt](https://github.com/ENCODE-DCC/rna-seq-pipeline/files/3891919/screenlog1.txt)

And here is my default conf file ~/.caper/default.conf
`[defaults]
cromwell=cromwell-47.jar
java-heap-server=8G

backend=gcp

out-dir=/srv/scratch/caper_out
tmp-dir=/srv/scratch/caper_tmp

#gcp-prj=[YOUR_GOOGLE_PROJECT]
gcp-prj=atac-rna-corr-pipeline

#out-gcs-bucket=[YOUR_OUTPUT_BUCKET_FOR_CAPER]
#tmp-gcs-bucket=[YOUR_TMP_BUCKET_FOR_CAPER]
out-gcs-bucket=gs://rna_caper/caper_out
tmp-gcs-bucket=gs://rna_caper/caper_tmp

max-concurrent-workflows=100`

**Comment by leepc12** [comment]
This doesn't look like a full log. Can you upload a full version of the log including Caper's automatic troubleshooting/debugging part at the end? Also, please increase disk size in your input JSON and try again? The default 100 HDD can be too small.

**Comment by firdaaminy** [comment]
Thank you for your reply. 

I tried to run the pipeline again by changing the input JSON file into:
{
"rna.endedness" : "paired",
"rna.fastqs_R1" : [["gs://rna_caper/inputs/ENCSR653DFZ_rep1_chr19_10000reads_R1.fastq.gz"], ["gs://rna_caper/inputs/ENCSR653DFZ_rep2_chr19_10000reads_R1.fastq.gz"]],
"rna.fastqs_R2" : [["gs://rna_caper/inputs/ENCSR653DFZ_rep1_chr19_10000reads_R2.fastq.gz"], ["gs://rna_caper/inputs/ENCSR653DFZ_rep2_chr19_10000reads_R2.fastq.gz"]],
"rna.align_index" : "gs://rna_caper/reference/GRCh38_v24_ERCC_phiX_starIndex_chr19only.tgz",
"rna.rsem_index" : "gs://rna_caper/reference/GRCh38_v24_ERCC_phiX_rsemIndex_chr19only.tgz",
"rna.kallisto_index" : "gs://rna_caper/reference/Homo_sapiens.GRCh38.cdna.all.chr19_ERCC_phix_k31_kallisto.idx",
"rna.bamroot" : "PE_stranded",
"rna.strandedness" : "stranded",
"rna.strandedness_direction" : "reverse",
"rna.chrom_sizes" : "gs://rna_caper/reference/GRCh38_EBV.chrom.sizes",
"rna.align_ncpus" : 16,
"rna.align_ramGB" : 60,
"rna.rsem_ncpus" : 16,
"rna.rsem_ramGB" : 60,
"rna.kallisto_number_of_threads" : 8,
"rna.kallisto_ramGB" : 30,
"rna.rna_qc_tr_id_to_gene_type_tsv" : "gs://rna_caper/reference/gencodeV24pri-tRNAs-ERCC-phiX.transcript_id_to_genes.tsv",
"rna.bam_to_signals_ncpus" : 8,
"rna.bam_to_signals_ramGB" : 30,
"rna.align_disk" : "local-disk 200 HDD",
"rna.kallisto_disk" : "local-disk 200 HDD",
"rna.rna_qc_disk" : "local-disk 200 HDD",
"rna.bam_to_signals_disk" : "local-disk 200 HDD",
"rna.mad_qc_disk" : "local-disk 200 HDD",
"rna.rsem_disk" : "local-disk 200 HDD"
}
but then the pipeline stopped in the middle of initializing rna.kallisto. I tried to find out why this happened and even changed back the input.json like the instructions in the beginning, however it kept reoccured. 

So I'm running this pipeline in the Ubuntu VM instance on GCP, with the specifications as following: 8 vCPUs, 52 GB memory, and an additional 500 GB disk. Do you have any recommendations on how to manage those resources in the input.json so that it will optimize the pipeline workflow? 

And here is the full version of the log
[screenlog_1.txt](https://github.com/ENCODE-DCC/rna-seq-pipeline/files/3915341/screenlog_1.txt)

Thank you very much for your constant help and your understanding

**Comment by firdaaminy** [comment]
Hello, good afternoon

I'm writing here again because I have a couple of questions I would like to ask regarding the initialization of rna.align.

So I did change the input.json to configure the resources. And just like you recommended, I changed it into:
`{
    "rna.endedness" : "paired",
    "rna.fastqs_R1" : [["gs://rna_caper2/inputs/ENCSR653DFZ_rep1_chr19_10000reads_R1.fastq.gz"], ["gs://rna_caper2/inputs/ENCSR653DFZ_rep2_chr19_10000reads_R1.fastq.gz"]],
    "rna.fastqs_R2" : [["gs://rna_caper2/inputs/ENCSR653DFZ_rep1_chr19_10000reads_R2.fastq.gz"], ["gs://rna_caper2/inputs/ENCSR653DFZ_rep2_chr19_10000reads_R2.fastq.gz"]],
    "rna.align_index" : "gs://rna_caper2/reference/GRCh38_v24_ERCC_phiX_starIndex_chr19only.tgz",
    "rna.rsem_index" : "gs://rna_caper2/reference/GRCh38_v24_ERCC_phiX_rsemIndex_chr19only.tgz",
    "rna.kallisto_index" : "gs://rna_caper2/reference/Homo_sapiens.GRCh38.cdna.all.chr19_ERCC_phix_k31_kallisto.idx",
    "rna.bamroot" : "PE_stranded",
    "rna.strandedness" : "stranded",
    "rna.strandedness_direction" : "reverse",
    "rna.chrom_sizes" : "gs://rna_caper2/reference/GRCh38_EBV.chrom.sizes",
    "rna.align_ncpus" : 16,
    "rna.align_ramGB" : 60,
    "rna.rsem_ncpus" : 16,
    "rna.rsem_ramGB" : 60,
    "rna.kallisto_number_of_threads" : 8,
    "rna.kallisto_ramGB" : 30,
    "rna.rna_qc_tr_id_to_gene_type_tsv" : "gs://rna_caper2/reference/gencodeV24pri-tRNAs-ERCC-phiX.transcript_id_to_genes.tsv",
    "rna.bam_to_signals_ncpus" : 8,
    "rna.bam_to_signals_ramGB" : 30,
    "rna.align_disk" : "local-disk 200 SSD",
    "rna.kallisto_disk" : "local-disk 200 SSD",
    "rna.rna_qc_disk" : "local-disk 200 SSD",
    "rna.bam_to_signals_disk" : "local-disk 200 SSD",
    "rna.mad_qc_disk" : "local-disk 200 SSD",
    "rna.rsem_disk" : "local-disk 200 SSD"
}`

Fortunately, the program didn't stop at the step of initializing rna.kallisto, as I previously mentioned. However, I do still stumbled upon the same problem in which the pipeline failed to start the rna.align process. I tried to change the resource configuration again a couple of times, but none of it work. Here I attached the workflow logs.
[workflow.4f99f858-7601-4b29-be18-ef3e5114a816.log](https://github.com/ENCODE-DCC/rna-seq-pipeline/files/3938105/workflow.4f99f858-7601-4b29-be18-ef3e5114a816.log)

I do hope you are willing to give me some insights as to why this error keeps reoccurring. I appreciate your answers very much. Thank you for your understanding and the time you spend to read this question of mine.

**Comment by ottojolanki** [comment]
Hi,
have you been able to run any workflows in this google cloud project? In case you have not, we should rule out that the problem is not in the configuration of the permissions (is the server machine allowed to spin up other machines, use required google cloud APIs etc.).

**Comment by firdaaminy** [comment]
Hi, sorry for the late reply.
Yes I did, I ran the previous RNA-seq pipeline with Cromwell

**Comment by firdaaminy** [comment]
Do you have any recommendations on how to solve the aligning step that keeps failing?

![image](https://user-images.githubusercontent.com/13981074/71345154-e5007500-25a7-11ea-9f28-0cf47422cb8b.png)

Do I need to change the configuration of the resources? All I did was following the tutorial steps exactly as mentioned

**Comment by ottojolanki** [comment]
The resources seem fine. Could you try to run this with cromwell as you did before (using the new pipeline version), to see if the problem would be somewhere between caper and cromwell? Sorry, I am having hard time figuring this one out..

**Comment by ottojolanki** [comment]
What kind of machine you are running caper server on?

**Comment by ottojolanki** [comment]
I am not entirely certain which availability zone caper defaults to, so you should try explicitly defining the gcp-zone (https://github.com/ENCODE-DCC/caper/blob/a909e3228510efade228d7187ef15890f5ae3ba9/DETAILS.md) in your caper configuration. Make sure that you have enough resources quoted in that zone (cpus and disk) by looking at iam/admin/quotas on your google cloud console.

**Comment by ottojolanki** [comment]
I tried, and failed to reproduce the issue using current master (https://github.com/ENCODE-DCC/rna-seq-pipeline/commit/202899508dc811a3a08bac6c2ce4ec47aa486192) branch. My input json is the same as the one you pasted above:
```
{
  "rna.endedness": "paired",
  "rna.fastqs_R1": [
    [
      "gs://documentation_runs/issuetestinput/ENCSR653DFZ_rep1_chr19_10000reads_R1.fastq.gz"
    ],
    [
      "gs://documentation_runs/issuetestinput/ENCSR653DFZ_rep2_chr19_10000reads_R1.fastq.gz"
    ]
  ],
  "rna.fastqs_R2": [
    [
      "gs://documentation_runs/issuetestinput/ENCSR653DFZ_rep1_chr19_10000reads_R2.fastq.gz"
    ],
    [
      "gs://documentation_runs/issuetestinput/ENCSR653DFZ_rep2_chr19_10000reads_R2.fastq.gz"
    ]
  ],
  "rna.align_index": "gs://documentation_runs/issuetestinput/GRCh38_v24_ERCC_phiX_starIndex_chr19only.tgz",
  "rna.rsem_index": "gs://documentation_runs/issuetestinput/GRCh38_v24_ERCC_phiX_rsemIndex_chr19only.tgz",
  "rna.kallisto_index": "gs://documentation_runs/issuetestinput/Homo_sapiens.GRCh38.cdna.all.chr19_ERCC_phix_k31_kallisto.idx",
  "rna.bamroot": "PE_stranded",
  "rna.strandedness": "stranded",
  "rna.strandedness_direction": "reverse",
  "rna.chrom_sizes": "gs://documentation_runs/issuetestinput/GRCh38_EBV.chrom.sizes",
  "rna.align_ncpus": 16,
  "rna.align_ramGB": 60,
  "rna.rsem_ncpus": 16,
  "rna.rsem_ramGB": 60,
  "rna.kallisto_number_of_threads": 8,
  "rna.kallisto_ramGB": 30,
  "rna.rna_qc_tr_id_to_gene_type_tsv": "gs://documentation_runs/issuetestinput/gencodeV24pri-tRNAs-ERCC-phiX.transcript_id_to_genes.tsv",
  "rna.bam_to_signals_ncpus": 8,
  "rna.bam_to_signals_ramGB": 30,
  "rna.align_disk": "local-disk 100 HDD",
  "rna.kallisto_disk": "local-disk 100 HDD",
  "rna.rna_qc_disk": "local-disk 100 HDD",
  "rna.bam_to_signals_disk": "local-disk 100 HDD",
  "rna.mad_qc_disk": "local-disk 100 HDD",
  "rna.rsem_disk": "local-disk 100 HDD"
}
```
Without reproducing the error it is hard for me to know how to fix this. In addition to the suggestions in the above comments, you should also make sure you are running the version of the pipeline you think you are running (maybe remove and reclone to be absolutely sure), using the input file you think you are using etc. I don't mean to sound patronizing, it is only that I am a little bit at my wit's end..
