### ISSUE TITLE
Starting with BAMs

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [ENCODE-DCC/rna-seq-pipeline#55]
@ottojolanki 
I wanted to run this pipeline starting with BAMs. 

I could not find documentation for how to do that.
I have version 1.1 of this pipeline. 

I assume there is a way to begin using the pipeline starting with BAMs. 
However, how would I know whether the BAMs I have are "genomebams" or "annobams" according to the pipeline?

**Comment by YogiOnBioinformatics** [comment]
@ottojolanki just wanted to follow up on this.

**Comment by ottojolanki** [comment]
@YogiOnBioinformatics there is no way to start this pipeline from other than fastq inputs for now, unfortunately. I know this is a desired feature, and will implement this in future (although this is not a high priority, unfortunately).
