### ISSUE TITLE
HTML QC Report

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [ENCODE-DCC/rna-seq-pipeline#57]
Out of curiosity, are you planning on adding QC HTML reports? 

These types of reports are available for both the ChIP and ATAC-Seq data. 
They contain extremely useful information AND graphs which are organized really well. 

It would wonderful if this functionality could be added in the future!

**Comment by ottojolanki** [comment]
Noted. I will make an idea ticket about this. Thank you for the feedback!

**Comment by YogiOnBioinformatics** [comment]
@ottojolanki that would be very much appreciated! 
Thanks very much for this wonderful pipeline regardless!
