### ISSUE TITLE
caper

### ISSUE THREAD

**Issue by summer-lemon** [ENCODE-DCC/rna-seq-pipeline#67]
I want to ask a question.
If I have multiple RNA-seq data and want to use this pipeline analysis at the same time, they will call software at the same time, such as caper, will this affect their results? That is, can I run multiple data at the same time?

**Comment by ottojolanki** [comment]
You can run multiple pipelines at the same time. The only limiting factor is the computational resources available to you. Everything runs in isolation and the results will not be affected by this.

**Comment by summer-lemon** [comment]
Ok, thank you
