### ISSUE TITLE
bedGraphToBigWig: needLargeMem: trying to allocate 0 bytes (limit: 100000000000)

### ISSUE THREAD

**Issue by summer-lemon** [ENCODE-DCC/rna-seq-pipeline#68]
When I use bedGraphToBigWig, the error is as follows:
"needLargeMem: trying to allocate 0 bytes (limit: 100000000000)".
.bw file and .bg file are empty

**Comment by ottojolanki** [comment]
Looks like you are running out of memory. Try increasing `"rna.bam_to_signals_ramGB"`.

**Comment by summer-lemon** [comment]
I set the "rna.bam_to_signals_ramGB": 100, but still the same error, I will try again.
