### ISSUE TITLE
Running in Google Cloud fails with: Scopes not configured for service account

### ISSUE THREAD

**Issue by TomGardner** [ENCODE-DCC/rna-seq-pipeline#71]
The full error is (yes the 'Scoped' and 'createScoped' seem to be misspelled):
`cromwell.core.CromwellFatalException: java.io.IOException: Scopes not configured for service account. Scoped should be specified by calling createScoped or passing scopes to constructor.`

The caper command I ran was:
`caper run rna-seq-pipeline.wdl -i input.json -b gcp --gcp-prj skygenic --gcp-out-dir gs://bucket-name/outputs/ --gcp-loc-dir gs://bucket-name/local/ -m testrun_metadata.json`

I could see in the logs the Cromwell command was:
```
python3 $(which align.py) \
    --fastqs_R1 /cromwell_root/rna-seq-pipeline/inputs/ENCSR653DFZ_rep2_chr19_10000reads_R1.fastq.gz \
    --fastqs_R2 /cromwell_root/rna-seq-pipeline/inputs/ENCSR653DFZ_rep2_chr19_10000reads_R2.fastq.gz \
    --endedness paired \
    --index /cromwell_root/rna-seq-pipeline/reference/GRCh38_v24_ERCC_phiX_starIndex_chr19only.tgz \
    --bamroot rep2PE_stranded \
    --ncpus 2 \
    --ramGB 4`
```
I tried to run both as the default user (me), and by exporting path to service account credential file via GOOGLE_APPLICATION_CREDENTIALS (which I don't see how that could work - but I tried it).
Same result.

Seems there should be a way to have credentials set before Cromwell is run.

**Comment by ottojolanki** [comment]
For details on caper configuration on GCP, please refer to caper documentation in: https://github.com/ENCODE-DCC/caper/blob/master/docs/conf_gcp.md 
If you plan on running more than couple pipeline runs, I recommend you run caper in server mode.

**Comment by TomGardner** [comment]
I think what's missing for me with running caper on GCP is the last section 'How to run Caper with a service account' - I have all the previous setup done for my service account.  How do I tell caper to use it?  Is there a parameter to pass with the path to the JSON credential file?  Is there an environment variable? Do I have to setup a Caper server?

**Comment by TomGardner** [comment]
I think I found the flag I need: --gcp-service-account-key-json in caper README.md

**Comment by TomGardner** [comment]
Ok. It works with the --gcp-service-account-key-json flag.
It failed the first time on bam_to_signals - I had to up the memory and cpus in the input.json file.
Then it worked.
