### ISSUE TITLE
Can't find log.final.out

### ISSUE THREAD

**Issue by ishujain4695** [ENCODE-DCC/rna-seq-pipeline#81]
Hi I am trying to run the pipeline on GCP. It is single ended RNA seq for 6 samples and 3 biological replicates.
This is what the error log says, after it runs the STAR command the error comes where it cannot find the log.final.out file. I don't get it.

2021/06/12 00:46:05 Starting container setup.
2021/06/12 00:46:07 Done container setup.
2021/06/12 00:46:09 Starting localization.
2021/06/12 00:46:15 Localization script execution started...
2021/06/12 00:46:15 Localizing input gs://caper-data/scripts/resource_monitor/resource_monitor.sh -> /cromwell_root/monitoring.sh
2021/06/12 00:46:16 Localizing input gs://rnaseqdata/input1/01_C1FN_S25_R1.fastq.gz -> /cromwell_root/rnaseqdata/input1/01_C1FN_S25_R1.fastq.gz
2021/06/12 00:46:24 Localizing input gs://rnaseqdata/ENCFF598IDH.tgz -> /cromwell_root/rnaseqdata/ENCFF598IDH.tgz
2021/06/12 00:51:54 Localizing input gs://rnaseqdata/output1/rna/4d6f9a46-d8b5-492a-8b56-a7a24e061d72/call-align/shard-0/script -> /cromwell_root/script
2021/06/12 00:51:56 Localization script execution complete.
2021/06/12 00:52:00 Done localization.
2021/06/12 00:52:00 Running user action: docker run -v /mnt/local-disk:/cromwell_root --entrypoint=/bin/bash encodedcc/rna-seq-pipeline@sha256:bdcac4249199303e3742c3635e3874df40dc11943f1809ec23f17f07a0b81ce9 /cromwell_root/script
2021-06-12 00:58:25,283 | INFO | __main__: Creating a single-ended aligner.
2021-06-12 00:58:25,314 | INFO | __main__: running STAR command STAR --genomeDir out --readFilesIn /cromwell_root/rnaseqdata/input1/01_C1FN_S25_R1.fastq.gz --readFilesCommand zcat --runThreadN 3 --genomeLoad NoSharedMemory --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverReadLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --outSAMheaderCommentFile COfile.txt --outSAMheaderHD @HD VN:1.4 SO:coordinate --outSAMunmapped Within --outFilterType BySJout --outSAMattributes NH HI AS NM MD --outSAMstrandField intronMotif --outSAMtype BAM SortedByCoordinate --quantMode TranscriptomeSAM --sjdbScore 1 --limitBAMsortRAM 14000000000
Jun 12 00:58:25 ..... Started STAR run
Jun 12 00:58:25 ..... Loading genome
Traceback (most recent call last):
  File "/software/rna-seq-pipeline/src/align.py", line 340, in <module>
    main(args)
  File "/software/rna-seq-pipeline/src/align.py", line 264, in main
    os.rename(os.path.join(cwd, "Log.final.out"), star_log_path)
FileNotFoundError: [Errno 2] No such file or directory: '/cromwell_root/Log.final.out' -> '/cromwell_root/rep1HSCepi_Log.final.out'
2021/06/12 01:00:45 Starting delocalization.
2021/06/12 01:00:46 Delocalization script execution started...
2021/06/12 01:00:46 Delocalizing output /cromwell_root/memory_retry_rc -> gs://rnaseqdata/output1/rna/4d6f9a46-d8b5-492a-8b56-a7a24e061d72/call-align/shard-0/memory_retry_rc
2021/06/12 01:00:46 Delocalizing output /cromwell_root/rc -> gs://rnaseqdata/output1/rna/4d6f9a46-d8b5-492a-8b56-a7a24e061d72/call-align/shard-0/rc
2021/06/12 01:00:53 Delocalizing output /cromwell_root/monitoring.log -> gs://rnaseqdata/output1/rna/4d6f9a46-d8b5-492a-8b56-a7a24e061d72/call-align/shard-0/monitoring.log
2021/06/12 01:00:54 Delocalizing output /cromwell_root/stdout -> gs://rnaseqdata/output1/rna/4d6f9a46-d8b5-492a-8b56-a7a24e061d72/call-align/shard-0/stdout
2021/06/12 01:00:55 Delocalizing output /cromwell_root/stderr -> gs://rnaseqdata/output1/rna/4d6f9a46-d8b5-492a-8b56-a7a24e061d72/call-align/shard-0/stderr
2021/06/12 01:00:56 Delocalizing output /cromwell_root/rep1HSCepi_Log.final.json -> gs://rnaseqdata/output1/rna/4d6f9a46-d8b5-492a-8b56-a7a24e061d72/call-align/shard-0/rep1HSCepi_Log.final.json
Required file output '/cromwell_root/rep1HSCepi_Log.final.json' does not exist.

**Comment by ottojolanki** [comment]
Hi, @ishujain4695 could you show me your input.json file, please?

**Comment by ishujain4695** [comment]
Hi,
Yes! Here it is:
{
    "rna.endedness" : "single",
    "rna.fastqs_R1" : [["gs://rnaseqdata/input1/01_C1FN_S25_R1.fastq.gz"],["gs://rnaseqdata/input1/01_C1FN_S25_R2.fastq.gz"],["gs://rnaseqdata/input1/01_C1FN_S25_R3.fastq.gz"]],
    "rna.fastqs_R2" : [],
	"rna.align_index" : "gs://rnaseqdata/ENCFF598IDH.tar.gz",
    "rna.rsem_index" : "gs://rnaseqdata/ENCFF285DRD/.tar.gz",
    "rna.bamroot" : "HSCepi",
    "rna.strandedness" : "unstranded",
    "rna.strandedness_direction": "unstranded",
    "rna.chrom_sizes" : "gs://rnaseqdata/GRCh38_EBV.chrom.sizes.tsv",
    "rna.align_ncpus" : 3,
    "rna.align_ramGB" : 14,
	"rna.run_kallisto" : "false",
    
    
    "rna.rna_qc_tr_id_to_gene_type_tsv" : "gs://rnaseqdata/gencodeV29pri-UCSC-tRNAs-ERCC-phiX.transcript_id_to_genes.tsv",
    "rna.bam_to_signals_ncpus" : 3,
    "rna.bam_to_signals_ramGB" : 14,
    "rna.rsem_ncpus" : 3,
    "rna.rsem_ramGB" : 14,
    "rna.align_disk" : "local-disk 150 SSD",
    
    "rna.rna_qc_disk" : "local-disk 150 SSD",
    "rna.mad_qc_disk" : "local-disk 150 SSD",
    "rna.bam_to_signals_disk" : "local-disk 150 SSD",
    "rna.rsem_disk" : "local-disk 150 SSD"
}

**Comment by ishujain4695** [comment]
{
    "rna.endedness" : "single",
    "rna.fastqs_R1" : [["gs://rnaseqdata/input1/01_C1FN_S25_R1.fastq.gz"],["gs://rnaseqdata/input1/01_C1FN_S25_R2.fastq.gz"],["gs://rnaseqdata/input1/01_C1FN_S25_R3.fastq.gz"]],
    "rna.fastqs_R2" : [],
	"rna.align_index" : "gs://rnaseqdata/ENCFF598IDH.tar.gz",
    "rna.rsem_index" : "gs://rnaseqdata/ENCFF285DRD.tar.gz",
    "rna.bamroot" : "HSCepi",
    "rna.strandedness" : "unstranded",
    "rna.strandedness_direction": "unstranded",
    "rna.chrom_sizes" : "gs://rnaseqdata/GRCh38_EBV.chrom.sizes.tsv",
    "rna.align_ncpus" : 3,
    "rna.align_ramGB" : 14,
	"rna.run_kallisto" : "false",
    "rna.rna_qc_tr_id_to_gene_type_tsv" : "gs://rnaseqdata/gencodeV29pri-UCSC-tRNAs-ERCC-phiX.transcript_id_to_genes.tsv",
    "rna.bam_to_signals_ncpus" : 3,
    "rna.bam_to_signals_ramGB" : 14,
    "rna.rsem_ncpus" : 3,
    "rna.rsem_ramGB" : 14,
    "rna.align_disk" : "local-disk 150 SSD",
    "rna.rna_qc_disk" : "local-disk 150 SSD",
    "rna.mad_qc_disk" : "local-disk 150 SSD",
    "rna.bam_to_signals_disk" : "local-disk 150 SSD",
    "rna.rsem_disk" : "local-disk 150 SSD"
}

**Comment by ottojolanki** [comment]
Seems likely you are running out of memory in the mapping stage (STAR seems to sometimes fail quietly in these cases and you only notice when the outputs are missing). See https://github.com/ENCODE-DCC/rna-seq-pipeline/blob/master/docs/reference.md#note-about-resources for advice.
