### ISSUE TITLE
Schematic Describing Pipeline?

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [ENCODE-DCC/rna-seq-pipeline#85]
@ottojolanki @strattan @leepc12 

Is there a schematic describing this pipeline similar to the [ATAC-Seq Pipeline](https://www.encodeproject.org/images/14be5217-09c8-441a-a1d9-b442a4aab68c/@@download/attachment/ATAC_unreplicated_200728.png)?

The online schematics for RNA-Seq pipelines seem to either be the long read RNA-Seq pipeline or the short-read RNA-Seq pipeline as opposed to this "REGULAR" RNA-Seq pipeline.

**Comment by ottojolanki** [comment]
Hi,
the pipeline schematic you are looking for is https://www.encodeproject.org/pipelines/ENCPL862USL/

**Comment by YogiOnBioinformatics** [comment]
Perfect! Thanks so much.
