### ISSUE TITLE
Running with Conda Environment?

### ISSUE THREAD

**Issue by CharaiCC** [ENCODE-DCC/rna-seq-pipeline#86]
I was trying to run this pipeline alongside the ENCODE-ATAC-seq-pipeline on an SGE-SMP server, but it just wasn't having it (missing packages, manually pointing it to binaries, etc). 

I was testing my run using the provided test data, submitting my job via caper, and changed the paths in the json to the correct directories. ATAC-seq runs fine without me setting up docker/singularity

I created a separate conda environment for both (the atac-seq one has its own environment script from the github), and I was wondering if there are plans to create a conda environment script for this as well? Or, if there is a txt file that could be provided with what packages are needed? I know reference.md lists software, but is that all the packages and is it even possible to run this on my server?

Sorry if my questions are too vague and plentiful, I'm still young in bioinformatics.

**Comment by ottojolanki** [comment]
Hi, unfortunately this pipeline does not support running with conda. You should look into running with docker or singularity.
