### ISSUE TITLE
unknown option --fastqs_R1

### ISSUE THREAD

**Issue by jaavedm** [ENCODE-DCC/rna-seq-pipeline#88]
I cannot get this pipeline to run using docker on my Ubuntu Linux System. I'm following the directions under
`https://github.com/ENCODE-DCC/rna-seq-pipeline/blob/dev/docs/howto.md#local-with-docker`

I run the pipeline using this command:
`caper run rna-seq-pipeline/rna-seq-pipeline.wdl -i myconfig.json --docker`

Deep within the cromwell.out file, I find the first occurrence of an error coming from the alignment step. That is, the `stderr `file in directory `e927560b-0a6c-4295-9881-5aeeac670024/call-align/shard-0/execution/stderr` has this output:

```
unknown option --fastqs_R1
usage: python3 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
```

In the `script `file within this same directory has this command:

```
python3 $(which align.py) \
    --fastqs_R1 e927560b-0a6c-4295-9881-5aeeac670024/call-align/shard-0/inputs/1469436948/D5Chon_RNA_bio1_1.fastq.gz \
    --fastqs_R2 e927560b-0a6c-4295-9881-5aeeac670024/call-align/shard-0/inputs/1469436948/D5Chon_RNA_bio1_2.fastq.gz \
    --endedness paired \
    --index e927560b-0a6c-4295-9881-5aeeac670024/call-align/shard-0/inputs/-2119211689/GRCh38_V29_STAR_index.tgz \
    --bamroot rep1meow \
    --ncpus 12 \
    --ramGB 16
) 
```

So, "`which align.py`" is not being resolved correctly. How should I configure the pipeline to find this directory?

**Comment by westonkjones** [comment]
I was having the same issue for `align.py` and `kallisto_quant.py`, though I'm running via SLURM because I was having trouble with the singularity image. Anyway, here's what I did to get past this.

In the caper docs it mentions:
```
If you see an error message like caper: command not found then add the following line to the bottom of ~/.bashrc and re-login.

export PATH=$PATH:~/.local/bin
```

The error I'm seeing shows the path that it's looking for these files in (won't post for anonymity) . I first tried to add the `rna-seq-pipeline/src` directory which contains these files to the PATH, but that didn't work despite them showing up in the path list. So I just manually copied the contents of `rna-seq-pipeline/src` (which contains align.py and kallisto_quant.py) to `~/.local/bin` and that seemed to work. Maybe this gives you a rabbit hole to go down to solve the same issue in Docker maybe just this would fix it 
```
...
RUN cp rna-seq-pipeline/src/* ~/.local/bin
...
```

**Comment by jaavedm** [comment]
I've finally gotten the pipeline to run with singularity with a lot of trial and error. Some updates to the documentation is necessary since it is unclear how to get this pipeline running locally. I think I've taken the long way to get this pipeline running and since I'm a newbie to docker and singularity, there could be other optimized ways to do what I've written below. 

Here is how I solved my problem:

1.  I've assumed that you've already googled around on how to install docker and singularity. I won't go into the details here, but get those two software packages installed first. 
2. Next, install a docker image using the Dockerfile in the rna-seq-pipeline directory
```
cd rna-seq-pipeline
docker image build -t encodedcc/rna-seq-pipeline:1.2.4 .
docker image ls
```

You should see the docker image installed with the ls command. Something like this:
```
REPOSITORY                   TAG       IMAGE ID       CREATED         SIZE
encodedcc/rna-seq-pipeline   1.2.4     1e14b543f8b1   11 hours ago    1.33GB
```

3. Using singularity, convert this docker image to a .sif (singularity image file) using the command
`singularity build rna-seq-pipeline.sif docker-daemon://encodedcc/rna-seq-pipeline:1.2.4`

4. If you have anything in your `input.json` file that points to local directories (for example index files for STAR, Kallisto, etc), be sure to bind those paths with singularity environment variable `SINGULARITY_BIND`. See [here ](https://sylabs.io/guides/3.0/user-guide/bind_paths_and_mounts.html) for instructions on how to do this. 
Specifically, in my `input.json` file I have lines that look like this. 
```
    "rna.align_index" : "/storage/genomics/encode/ENCFF598IDH_GRCh38_V29_STAR_index.tgz",
    "rna.rsem_index" : "/storage/genomics/encode/ENCFF285DRD_GRCh38_V29_RSEM_index.tgz",
```
For singularity to know what the "/storage" folder is on my local system (i.e. outside the singularity container). I needed to bind this path by running 

`export SINGULARITY_BIND="/storage"`

If you fail to do this, then the scripts would fail with error messages resembling this:

`FileNotFoundError: [Errno 2] No such file or directory: '089ab630-4366-4f8b-a0c9-e856eabbb8ca/call-align/shard-3/inputs/-2119211689/ENCFF598IDH_GRCh38_V29_STAR_index.tgz'`

5. Finally, run caper using this command:
`caper run rna-seq-pipeline.wdl -i input.json --singularity rna-seq-pipeline.sif`
